# site settings
title: Documentation
author: Spence
github_username: smatsushima1
repo: "https://github.com/smatsushima1/documentation"
description: Projects and documentation

# build settings
markdown: kramdown
theme: minima

