# site settings
title: Home
author: Spence
github_username: smatsushima1
repo: "https://github.com/smatsushima1/home"
description: Projects and documentation

# build settings
markdown: kramdown
theme: minima

