# site settings
title: Home
email: smatsushima1@gmail.com
github_username: smatsushima1
repo: "https://github.com/smatsushima1/home"
description: This site documents some of the most important things I've learned in my programming journey.

# build settings
markdown: kramdown
theme: minima

