# site settings
title: What I've Learned
author: Spence
email: smatsushima1@gmail.com
github_username: smatsushima1
repo: "https://github.com/smatsushima1/home"
description: This site documents some of the more important things I've learned in my programming journey.

# build settings
markdown: kramdown
theme: minima

