# site settings
title: Home
author: Spence
email: smatsushima1@gmail.com
github_username: smatsushima1
repo: "https://github.com/smatsushima1/home"
description: This site documents some of the most important things I've learned in my programming journey and will continue to be updated. I hope it will help in your journey as much as it does for me.

# build settings
markdown: kramdown
theme: minima

